### ISSUE TITLE
No handling for Windows binaries ending in .exe

### ISSUE THREAD

**Issue by zwass** [EverlastingBugstopper/binary-install#1]
Typically Windows binaries are published with a `.exe` extension. This package looks for something exactly matching the `name` parameter provided, which makes for an unexpected `You must install foo before you can run it` if the downloaded archive actually contains `foo.exe`.

I was able to work around this by explicitly changing the `name` for the Windows platform, but it could be nice to automatically handle the `.exe` extension.

**Comment by zwass** [comment]
The API documentation does indicate that `name` is the "binary name", in which case this does all seem consistent. Maybe the issue is just the example project which doesn't seem to handle Windows binaries properly.

**Comment by EverlastingBugstopper** [comment]
i'm honestly not too familiar with windows and how typical binary installers work with .exe vs. .tar.gz! Right now the repo is only meant to really work with .tar.gz binaries, but I'd be interested to see a PR with changes to the example repo + the lib if necessary to add support for .exe

**Comment by zwass** [comment]
I am also not a Windows expert, but my understanding is that there is not an "executable" permission in Windows like on Unix-y systems. Instead Windows just treats anything with `.exe` extension as executable.

So the contents of the `.tar.gz` file should be an executable with the suffix `.exe`. I'm going to be putting up a PR soon with my workaround and I can link it here.

**Comment by zwass** [comment]
Essentially I just added the `BINARY_NAME` field to the existing pattern you provided. See https://github.com/fleetdm/fleet/pull/52/files#diff-bc02553e5872d801830f8c85ad3e51981c79e74f585288de965573f7209df3b3R58.

**Comment by zwass** [comment]
Nice, thanks for getting to this!

**Comment by EverlastingBugstopper** [comment]
Thanks for the quick and easy example!
