### ISSUE TITLE
fix install location

### ISSUE THREAD

**Issue by EverlastingBugstopper** [EverlastingBugstopper/binary-install#11]
we should likely be installing this in `node_modules/.bin` instead of `node_modules/binary-install/bin`. it doesn't _super_ matter, just a little unexpected. I can't seem to figure out an elegant solution for this, help very welcome.

relevant code is here: https://github.com/EverlastingBugstopper/binary-install/blob/main/packages/binary-install/index.js#L45

**Comment by dncrews** [comment]
@EverlastingBugstopper would this be why `@apollo/rover` cli never stays installed unless it was the LAST thing installed? Every time I `yarn add` anything else, rover becomes uninstalled from `node_modules/binary-install/bin`. (If not, no worries; I'm just trying to track that down)

**Comment by EverlastingBugstopper** [comment]
!! Maybe? I've never heard of that problem happening before... Might help to add some `console.log` statements around the different functions to see if something is running when it shouldn't...

**Comment by EverlastingBugstopper** [comment]
fix has been merged
