### ISSUE TITLE
add cache feature

### ISSUE THREAD

**Issue by liudonghua123** [EverlastingBugstopper/binary-install#13]
I would like to vote to add some feature like check cache, if it does not hit then axios will download it. 
Sometimes my network is not stable, the installation process would not download the file successfully. If I know where the cache it stores, then I can put the file there.

**Comment by EverlastingBugstopper** [comment]
binary downloads are cached and should not be redownloaded. the next release will also allow configuring the `installDirectory` like so: `new Binary("my-binary", "https://example.com/my-binary/linux/v1.0.0.tar.gz", { "installDirectory": "./my-custom-directory" })`
