### ISSUE TITLE
Error state of downloading binary 

### ISSUE THREAD

**Issue by chawyehsu** [EverlastingBugstopper/binary-install#2]
The download progress is wrong and message gets printed too early.

![wrangler](https://user-images.githubusercontent.com/5764917/99906676-5f36fd80-2d13-11eb-9559-3dbd14eeb4b3.gif)

You can see that file size of the wrangler binary is increasing, which means the download does not finish. **But it already said `wrangler has been installed!` and it stuck in the state of waiting for the download complete.**

**Comment by chawyehsu** [comment]
I think it's related to https://github.com/cloudflare/binary-install/issues/3 reported by @magicdawn

**Comment by EverlastingBugstopper** [comment]
this should be fixed by #16
