### ISSUE TITLE
Impossible to uninstall with current API

### ISSUE THREAD

**Issue by WillsterJohnson** [EverlastingBugstopper/binary-install#25]
```js
 uninstall() {
    if (existsSync(this._getInstallDirectory())) {
      rimraf.sync(this.installDirectory);
      console.log(
        `${this.name ? this.name : "Your package"} has been uninstalled`
      );
    }
  }
```
This code was [removed in a refactor and never reintroduced](https://github.com/EverlastingBugstopper/binary-install/commit/ef66b8b8914c1e055c3dd5fd3e54d45c915cdb15#diff-3f7e2cf0d77d472a88f5c589fab180c64b2ac8126b1336ad19bb514f5c1ddf3e).
Was this intentional?

**Comment by EverlastingBugstopper** [comment]
uninstall logic was removed, yes - that code never ended up getting called and uninstalls/re-installs can be handled with npm/yarn
