### ISSUE TITLE
Can't Run Installed Binary: ENOENT

### ISSUE THREAD

**Issue by bnheise** [EverlastingBugstopper/binary-install#26]
I have binary-install successfully downloading my binary.

When I try to run it, though, I just get this error:

```
Error: spawnSync /Users/brianheise/test/node_modules/binary-install/node_modules/.bin/ce-cli ENOENT
```

I navigate to the folder and indeed it is empty. Elsewhere in the node modules folder, I was able to find a binary with my apps name. However, when I run it I get the exact same error. My guess is that binary-install creates this binary file that directs to another folder where my binary actually should be, except it's not there. Any ideas what could be causing that and how I can fix it?

**Comment by vladdoroniuk** [comment]
I've checked your binaries, you should put ce-cli.exe in the folder with exacatly the same name as .tar.gz package. So:
ce-cli-x86_64-pc-windows-gnu.tar.gz ---> ce-cli-x86_64-pc-windows-gnu --->ce-cli.exe
That could possibly fix the issue.

**Comment by bnheise** [comment]
That's what I had originally, but I changed it to what it is now because that wasn't working and now it works. I think the owner of the package must have updated how it works because when I checked the sourcecode, it wasn't trying to load from such a folder structure, though blogs that I had read said that it would.

**Comment by EverlastingBugstopper** [comment]
i believe this is fixed, closing the issue
