### ISSUE TITLE
Installating binaries to `envPaths().config` is problematic

### ISSUE THREAD

**Issue by thomaseizinger** [EverlastingBugstopper/binary-install#3]
The usage of `envPaths().config` as the default installation path is problematic for two reasons:

1. Storing the binaries outside of the project directory causes surprising behaviour in CI environments because one has to remember to cache those directories as well. Otherwise, the next CI run will fail to find the binary if only `node_modules` is being cached. It would be more resilient to put the binaries into `node_modules/.cache` or some other sub-directory within `node_modules`.

2. It violates the XDG directory specification. `$XDG_CONFIG_HOME` is meant for configuration files. Binaries are clearly not configuration files. If at all, we should be putting those binaries into `$XDG_CACHE_HOME`.

(2) is actually no longer an issue if we simply store the binaries within `node_modules`.

**Comment by EverlastingBugstopper** [comment]
the latest version places the binary in `node_modules`

**Comment by thomaseizinger** [comment]
> the latest version places the binary in `node_modules`

Ah thanks for pointing this out!

I actually opened this issue because of `wasm-pack` and didn't realize that there is already an issue for this: https://github.com/rustwasm/wasm-pack/issues/791
