### ISSUE TITLE
Binary name not found in example

### ISSUE THREAD

**Issue by okbrown** [EverlastingBugstopper/binary-install#8]
https://github.com/EverlastingBugstopper/binary-install/blob/9eb8d53a3b2b9afd03710f12d193d39200eddc64/packages/binary-install-example/binary.js#L67

Should this be `package.name` or `platformMetadata.BINARY_NAME`?

Also should the `supportedPlatforms` array also contain `BINARY_NAME`? by removing this and using it in the package.json with something like `binDependencies` allows it to be decoupled and allows for multiple binary installations.

I'm currently making some tweaks to get this to work to install a collection of binaries, hopefully will submit PR.

**Comment by EverlastingBugstopper** [comment]
this has been fixed
