### ISSUE TITLE
Download binary from private repo

### ISSUE THREAD

**Issue by mjbyrnes4664** [EverlastingBugstopper/binary-install#9]
When downloading a binary from a private repo you have to use the Github API URL of the form `https://api.github.com/repos/{owner}/{repo}/releases/assets/{asset_id}` which requires an `Authorization` header and an additional header of the form `Accept: 'application/octet-stream'` to download the asset. While the authorization token can be added to the URL with a `https://{token}@api.github.com/repos/{owner}/{repo}/releases/assets/{asset_id}`, the Accept header still needs to be passed

There isn't currently a way to affect the `axios` call within the `install` function. Could there be a `fetchOptions` parameter added to either the `install` function or the constructor that would allow a user to pass additional options to send to `axios`?

I'd be happy to submit a PR for the change

**Comment by EverlastingBugstopper** [comment]
this was merged back in #10, i'm working on cutting an actual release for this now
